/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.mathlark.larkv2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LarkV2Test {
    @Test void appHasAGreeting() {
        assertEquals(1, 1);
    }
}
